# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
# resolver: ghcjs-0.2.0.20151230.3_ghc-7.10.2
resolver: lts-3.5
compiler: ghcjs-0.2.0.20151230.3_ghc-7.10.2
compiler-check: match-exact
setup-info:
     ghcjs:
           source:
                  ghcjs-0.2.0.20151230.3_ghc-7.10.2:
                          url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20151230.3/ghcjs-0.2.0.20151230.3.tar.gz"

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: git@github.com:ryantrinkle/reflex-dom.git
    commit: 6a1c2cfb8f115fbc4abfb35b4c61f44d50e39bb0

extra-deps:
  - reglex-dom-0.2
  - reflex-0.3.2
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.3.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.10.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
